#!/bin/bash

echo "🎨 Mock App Icons Setup"
echo "========================"
echo ""
echo "To add artwork for the fake apps, place your PNG images in these locations:"
echo ""
echo "📁 Simmer/Assets.xcassets/MockAppIcons/"
echo "├── photogram.imageset/photogram.png (for PhotoGram)"
echo "├── bikbok.imageset/bikbok.png (for BikBok)"
echo "├── smudgify.imageset/smudgify.png (for Smudgify)"
echo "├── flixstream.imageset/flixstream.png (for FlixStream)"
echo "└── hilothere.imageset/hilothere.png (for HiLoThere)"
echo ""
echo "📋 Requirements:"
echo "- Use PNG format"
echo "- Recommended size: 60x60 pixels (1x), 120x120 pixels (2x), 180x180 pixels (3x)"
echo "- Square aspect ratio"
echo "- Transparent background preferred"
echo ""
echo "🔧 After adding images:"
echo "1. Open Simmer.xcodeproj in Xcode"
echo "2. The images will automatically appear in the asset catalog"
echo ""
echo "💡 Tips:"
echo "- You can use any app icon designs you create"
echo "- Make sure they're visually distinct from real app icons"
echo "- Consider using similar colors/styles to the real apps"
echo "- Test the mock data toggle (Cmd+M) to see your icons in action"
echo "- Mock apps: PhotoGram, BikBok, Smudgify, FlixStream, HiLoThere" 