name: Release

on:
  push:
    tags:
      - 'v*
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 150       
    - name: Cache Xcode derived data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-$[object Object][object Object] hashFiles('**/*.xcodeproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-
          
    - name: Build for Release
      run: |
        xcodebuild -project Simmer.xcodeproj \
          -scheme Simmer \
          -configuration Release \
          -derivedDataPath build \
          build
        
    - name: Create app bundle
      run: |
        mkdir -p Simmer.app/Contents/MacOS
        mkdir -p Simmer.app/Contents/Resources
        
        # Copy the built binary
        cp build/Build/Products/Release/Simmer Simmer.app/Contents/MacOS/
        
        # Copy Info.plist
        cp Simmer/Info.plist Simmer.app/Contents/
        
        # Copy assets
        cp -r Simmer/Assets.xcassets Simmer.app/Contents/Resources/
        
        # Make the app executable
        chmod +x Simmer.app/Contents/MacOS/Simmer
        
    - name: Create DMG
      run: |
        # Create a temporary directory for DMG contents
        mkdir -p dmg_temp
        
        # Copy the app to the temp directory
        cp -r Simmer.app dmg_temp/
        
        # Create DMG
        hdiutil create -volname "Simmer" -srcfolder dmg_temp -ov -format UDZO Simmer.dmg
        
        # Clean up
        rm -rf dmg_temp
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: simmer-app
        path: |
          Simmer.app
          Simmer.dmg
          
  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: simmer-app
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Simmer.app
          Simmer.dmg
        body: |
          ## Simmer v${{ github.ref_name }}
          
          A macOS menubar application for iOS Simulator management.
          
          ### Whats New
          - iOS Simulator management
          - App document management
          - Snapshot creation and restoration
          - Menubar integration
          
          ### Installation
          1. Download the DMG file
         2rag Simmer to your Applications folder
         3. Launch the app - it will appear in your menubar
          
          ### Features
          - **Simulator Management**: List and manage iOS simulators
          - **App Management**: View installed apps and their documents
          - **Document Management**: Access and manage app documents
          - **Snapshot Management**: Create and restore document snapshots
          
          ### System Requirements
          - macOS 14.0 or later
          - Xcode 15.0(for development)
          - iOS Simulator installed
          
          ### Permissions
          The app requires access to:
          - iOS Simulator data directory
          - File system access for document management
          - Finder integration
          
          ### Troubleshooting
          If the app doesn't appear in your menubar:
       1System Preferences > Security & Privacy
         2 Ensure the app is properly signed
          3essary permissions when prompted
          
          ### Development
          This is a learning project built with SwiftUI and AppKit.
          
          For more information, see the [README](https://github.com/${{ github.repository }}#readme).
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 